int min(int a, int b);
int max(int a, int b);
double Enteringfunction(int n, int k, int i, int j);
void InputMatrix(int n, int k, double *a, double *b, int first_row, int max_rows);
int fileInputMatrix(int n, char *name, double *a, double *b, double *x, int my_rank, int p);
void OutputMatrix(int l, int n, int m, double *a, double *x, int my_rank, int p);
void OutputAnswer(int m, double* answer);
int SolveSystem(int n, int* mass, double* a, double* b, double* x, double* y, double* answer, int my_rank, int p);
double SolutionAccuracy(int n, double* x);
double SolutionError(int n, double* a, double* b, double* x, double* y, double* answer, int my_rank, int p);
